JKSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("productos.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registro/', include("usuarios.urls")),
    path('carrito/', include("carritos.urls", namespace="carrito")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carritos/urls.py
from django.urls import path
from . import views


app_name = "carritos"
urlpatterns = [
    path('', views.carrito, name="compra"),
    path('update/', views.carrito_actualizado, name='update'),
    path('borrar_carrito/<int:carrito_id>', views.carrito_borrado, name="carrito_borrado"),

]

productos/urls.py
from django import urls
from django.urls import path, re_path
from . import views

from .views import SearchResultsView, categoria, contacto, listar

app_name = "productos"
urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('home/', views.home, name="home"),
    path('acerca/', views.acerca, name="acerca"),
    path('resultado/', SearchResultsView.as_view(), name="resultado"),
    path('producto/<int:producto_id>', views.producto, name="producto"),
    path('producto_nuevo', views.crear_producto, name="producto_nuevo"),
    path('editar_producto/<int:producto_id>', views.editar_producto, name="editar_producto"),
    path('borrar_producto/<int:producto_id>', views.producto_borrado, name="producto_borrado"),
    path('contacto/', contacto, name="contacto"),
    path('categoria/', categoria, name="categoria"),
    path('listar/', listar, name="listar"),



]

carritos/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import m2m_changed

from productos.models import Producto

User = settings.AUTH_USER_MODEL

class CarritoManager(models.Manager):
    def new_or_get(self, request):
        carrito_id = request.session.get("carrito_id", None)
        qs = self.get_queryset().filter(id=carrito_id)
        if qs.count() == 1:
            nuevo_carrito = False
            carrito_obj = qs.first()
            if request.user.is_authenticated and carrito_obj.usuario is None:
                carrito_obj.usuario = request.user
                carrito_obj.save()
        else:
            carrito_obj = Carrito.objects.new(usuario=request.user)
            nuevo_carrito = True
            request.session['carrito_id'] = carrito_obj.id
        return carrito_obj, nuevo_carrito

    def new(self, usuario=None):
        user_obj = None
        if usuario is not None:
            if usuario.is_authenticated:
                user_obj = usuario
        return self.model.objects.create(usuario=user_obj)

class Carrito(models.Model):
    usuario         = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    productos       = models.ManyToManyField(Producto, blank=True)
    total           = models.DecimalField(default=0.00, max_digits=50, decimal_places=2)
    updated         = models.DateTimeField(auto_now=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    objects = CarritoManager()

    def __str__(self):
        return str(self.id)


def total_carrito(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        productos = instance.productos.all()
        total = 0
        for x in productos:
            total += x.precio
        instance.total = total
        instance.save()
m2m_changed.connect(total_carrito, sender=Carrito.productos.through)

carritos/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages

from productos.models import Producto, Categoria
from .models import Carrito

def carrito(request):
    categorias = Categoria.objects.all()
    carrito_obj, nuevo_carrito = Carrito.objects.new_or_get(request)
    context = {
        'carrito': carrito_obj,
        'categorias': categorias,
    }
    return render(request, "carrito/carrito.html", context)

def carrito_actualizado(request):
    producto_id = request.POST.get('producto_id')
    if producto_id is not None:
        item = Producto.objects.get(id=producto_id)
        carrito_obj, nuevo_carrito = Carrito.objects.new_or_get(request)
        if item in carrito_obj.productos.all():
            carrito_obj.productos.remove(item)
        else:
            carrito_obj.productos.add(item)
            messages.success(request, "Producto Agregado")
    return redirect('carritos:compra')


def carrito_borrado(request, carrito_id):
    borrado = get_object_or_404(Carrito, id=carrito_id)
    messages.success(request, "Carro Eliminado")
    borrado.delete()
    return redirect("carritos:compra")

templates/carrito/actualizar_carrito.html
<form   method='POST' action="{% url 'carrito:update' %}"  class="d-flex">
    {% csrf_token %}
    <input type="hidden" name="producto_id" value="{{ producto.id }}">
    {% if producto in carrito.productos.all %}

        <button type="submit" class="btn btn-danger ms-3">Eliminar</button>
    {% else %}
        <button type="submit" class="btn btn-success ms-3">Agregar al carrito</button> 
    {% endif %} 
</form>
  

templates/carrito/carrito.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
{% url 'productos:home' as home %}


<div class="w3-padding-64 w3-content w3-text-grey" >

  <div class="container pb-5 mb-5">
    <h1 class="text-center">Carro de Compras</h1>
   

    {% if carrito.productos.exists %}

    <h3 class="container-sm pb-3"></h3>
    
    <table class="table container-sm col-4">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Producto</th>
            <th scope="col">Precio</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            {% for producto in carrito.productos.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ producto.titulo }}</td>
            <td>CLP $ {{ producto.precio | intcomma }}</td>
            <td>{% include 'carrito/actualizar_carrito.html' with producto=producto carrito=carrito %}        
            </td>
          </tr>
            {% endfor %}
          <tr>
            <td  colspan="2"></td>
            <td><b>Total</b> <span class="ps-2"> CLP $ {{ carrito.total | intcomma }}</span></td>
          </tr>
        </tbody>
      </table>
      <div class="d-flex justify-content-end my-5">
        <a href="{% url 'carrito:carrito_borrado' carrito.id %}" class="btn btn-danger mb-5 ms-5 me-3 px-3">Eliminar Carro</a>  
        <button class="btn btn-success mb-5 ms-5 me-3 px-3" id="miBoton" onclick="mostrarAlerta()">Comprar </button>
    </div>

    {% else %}
    <div class="lead text-center">
    <p class="lead text-center">Su carrito esta vacío, favor elegir un producto.</p>
    <a href="{% url 'productos:home' %}"  class="btn btn-success ms-3">Agregar Productos</a>

  </div>
    {% endif %}

</div>
<div class="abajo"></div>
        
</div>

<!-- Incluye Sweet Alert -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<script>
    function mostrarAlerta() {
        // Muestra la alerta de Sweet Alert
        Swal.fire({
            title: "Comprado",
            text: "{{m}}",
            icon: "success",
            timer: 1000,
        });
    }
</script>


{% endblock %}  