JKSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("productos.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registro/', include("usuarios.urls")),
    path('carrito/', include("carritos.urls", namespace="carrito")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django import urls
from django.urls import path, re_path
from . import views

from .views import SearchResultsView, categoria, contacto, listar

app_name = "productos"
urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('home/', views.home, name="home"),
    path('acerca/', views.acerca, name="acerca"),
    path('resultado/', SearchResultsView.as_view(), name="resultado"),
    path('producto/<int:producto_id>', views.producto, name="producto"),
    path('producto_nuevo', views.crear_producto, name="producto_nuevo"),
    path('editar_producto/<int:producto_id>', views.editar_producto, name="editar_producto"),
    path('borrar_producto/<int:producto_id>', views.producto_borrado, name="producto_borrado"),
    path('contacto/', contacto, name="contacto"),
    path('categoria/', categoria, name="categoria"),
    path('listar/', listar, name="listar"),



]

productos/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User


class Categoria(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return self.descripcion

class Producto(models.Model):
    titulo       = models.CharField(max_length=260, null=False)
    imagen       = models.ImageField(upload_to='imagenes/')
    descripcion  = models.TextField()
    precio       = models.DecimalField(decimal_places=0, max_digits=20)
    categoria    = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha        = models.DateField(null= False)
    urlpago      = models.URLField(null=True)
    admin        = models.ForeignKey(User, on_delete=models.CASCADE)
 
    def __str__(self):
        return self.titulo

class Contacto(models.Model):
    nombre = models.CharField(max_length=25)    
    correo = models.EmailField()
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

templates/base/footer.html
  <div class="w3-container" style="padding:150px 16px" >
    
      <footer class="w3-container w3-padding-64 w3-center w3-opacity">  
        <div class="w3-xlarge w3-padding-32">
          <i class="fa fa-facebook-official w3-hover-opacity"></i>
          <i class="fa fa-instagram w3-hover-opacity"></i>
          <i class="fa fa-twitter w3-hover-opacity"></i>
       </div>
       <p>Powered by <a href="" target="_blank">Parking Site</a></p>
      </footer>

  

templates/base/head.html
{% load static %}

<!-- Required meta tags -->
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />

<!-- Bootstrap CSS -->
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
  crossorigin="anonymous"/>
  
<link rel="stylesheet" href='{% static "css/style.css" %}' />
<link rel="icon" type="image/x-icon"  href='{% static "css/icono.png" %}' />
<title>Music Pro</title>

templates/base/header.html
{% url 'productos:home' as home %}
{% load static %}

templates/base/navbar.html
{% url 'productos:listar' as listar %}
{% url 'productos:home' as home %}
{% url 'productos:producto_nuevo' as nuevo %}
{% url 'productos:categoria' as categoria %}


<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Sidebar on click -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>

    <a class="w3-bar-item w3-button w3-padding-large w3-hide-small">PARKING SITE</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'productos:home' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">ESTACIONAMIENTO</a>
    {% if not perms.productos.add_producto %}
    {% endif %} 

    <a href="{% url 'logout'%}?next={{ inicio }}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">CERRAR SESION</a>
    <form method="GET" action="{% url 'productos:resultado' %}" class="w3-bar-item w3-hide-small w3-right w3-margin-right">
      <input class="w3-dropdown-hover w3-hide-small" type="search" name="q" placeholder="Buscar" aria-label="Search" value="{{ request.GET.q }}">
    </form>
    {% else %}
   
    
    <a href="{% url 'productos:home' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">PRODUCTOS</a>
    <form method="GET" action="{% url 'productos:resultado' %}" class="w3-bar-item w3-hide-small w3-right w3-margin-right">
      <input class="w3-dropdown-hover w3-hide-small" type="search" name="q" placeholder="Buscar" aria-label="Search" value="{{ request.GET.q }}">
      
    </form>
    {% endif %}


    {% if perms.app.view_producto %}
    <div class="w3-dropdown-hover w3-hide-small w3-right w3-margin-right ">
      <button class="w3-padding-large w3-button " title="More">ADMINISTRACION <i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
        <a href="{{ listar }}"  class="w3-bar-item w3-button">MENSAJES</a>
        <a href="{{ nuevo }}"  class="w3-bar-item w3-button">AGREGAR</a>
        <a href="{{ home }}"class="w3-bar-item w3-button">EDITAR</a>
        <a href="{{ categoria }}"class="w3-bar-item w3-button">COMUNA</a>
      </div>
      {% endif %}

        </div>
  
</div>
<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->
<div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">


  
  {% if request.user.is_authenticated %}
  <a href="{% url 'productos:home' %}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">PRODUCTOS</a>
  {% if not perms.productos.add_producto %}
  <a href="{% url 'productos:contacto' %}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CONTACTO</a>
  {% endif %} 
  <a href="{% url 'logout'%}?next={{ inicio }}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CERRAR SESION</a>
  {% else %}
  <a href="{% url 'login' %}"  class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">INICIAR SESION</a>
  <a href="{% url 'productos:contacto' %}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CONTACTO</a>
  <a href="{% url 'productos:home' %}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">PRODUCTOS</a>
  {% endif %}
  
  {% if perms.app.view_producto %}
  <a href="{{ lista }}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">MENSAJES</a>
  <a href="{{ nuevo }}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">AGREGAR</a>
  <a href="{{ home }}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">EDITAR</a>
  <a href="{{ categoria }}" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">MARCA</a>
  {% endif %}

</div>