JKSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("productos.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registro/', include("usuarios.urls")),
    path('carrito/', include("carritos.urls", namespace="carrito")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django import urls
from django.urls import path, re_path
from . import views

from .views import SearchResultsView, categoria, contacto, listar

app_name = "productos"
urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('home/', views.home, name="home"),
    path('acerca/', views.acerca, name="acerca"),
    path('resultado/', SearchResultsView.as_view(), name="resultado"),
    path('producto/<int:producto_id>', views.producto, name="producto"),
    path('producto_nuevo', views.crear_producto, name="producto_nuevo"),
    path('editar_producto/<int:producto_id>', views.editar_producto, name="editar_producto"),
    path('borrar_producto/<int:producto_id>', views.producto_borrado, name="producto_borrado"),
    path('contacto/', contacto, name="contacto"),
    path('categoria/', categoria, name="categoria"),
    path('listar/', listar, name="listar"),



]

productos/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User


class Categoria(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return self.descripcion

class Producto(models.Model):
    titulo       = models.CharField(max_length=260, null=False)
    imagen       = models.ImageField(upload_to='imagenes/')
    descripcion  = models.TextField()
    precio       = models.DecimalField(decimal_places=0, max_digits=20)
    categoria    = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha        = models.DateField(null= False)
    urlpago      = models.URLField(null=True)
    admin        = models.ForeignKey(User, on_delete=models.CASCADE)
 
    def __str__(self):
        return self.titulo

class Contacto(models.Model):
    nombre = models.CharField(max_length=25)    
    correo = models.EmailField()
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

productos/forms.py
from django import forms
from .models import Categoria, Contacto, Producto

class FormProducto(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('categoria', 'fecha', 'titulo', 'descripcion', 'precio', 'imagen', 'urlpago')
        widgets = {
            'categoria': forms.Select(
                attrs={
                    "class": "form-control",
                    "id": "categoria",
                }
            ),
            'fecha': forms.SelectDateWidget(
                attrs={
                    "class": "visually-hidden",
                }
            ),
            'titulo':forms.TextInput(
                attrs={
                    "class": "form-control",
                    "id": "titulo",
                }
            ),
            'descripcion': forms.Textarea(
                attrs={
                    "class": "form-control",
                    "id": "descripcion",
                }
            ),
            'precio': forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "id": "precio",
                }
            ),
            'urlpago': forms.TextInput(
                attrs={
                    "class": "form-control",
                    "id": 'urlpago',
                }
            ),
            
            'imagen': forms.ClearableFileInput(),
        }


# FORMULARIO CONTACTO
class ContactoForm(forms.ModelForm):
    nombre = forms.CharField(min_length=3, max_length=15) #VALIDACION 1
    class Meta:
        model = Contacto
        fields = '__all__'

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'

productos/views.py
from django.contrib.auth.models import User
from django.http import request
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic.base import TemplateView
from .forms import *
from django.db.models import Q
from django.views.generic.list import ListView
from django.utils import timezone
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404


from carritos.models import Carrito
from .models import Categoria, Producto

def inicio(request):
    productos13 = Producto.objects.all()
    categorias = Categoria.objects.all()
    context = {
        'primeros_productos': productos13,
        'categorias': categorias,
    }
    return render(request, "inicio.html", context)

def home(request):
    productos13 = Producto.objects.all()
    categorias = Categoria.objects.all()
    context = {
        'primeros_productos': productos13,
        'categorias': categorias,
    }
    return render(request, "home.html", context)

def acerca(request):
    categorias = Categoria.objects.all()
    context = {
        'categorias': categorias,
    }
    return render(request, "acerca.html", context)

@permission_required('app.view_producto')
def resultado(request, categoria_id):
    categoria_id = get_object_or_404(Categoria, id=categoria_id)
    categorias = Categoria.objects.all()
    context = {
        'categorias': categorias,
        'id_cat': categoria_id,
    }
    return render(request, "search/resultado.html", context)


def producto(request, producto_id):
    categorias = Categoria.objects.all()
    un_producto =get_object_or_404(Producto, id=producto_id)
    carrito_obj, nuevo_carrito = Carrito.objects.new_or_get(request)
    context = {
        'producto': un_producto,
        'categorias': categorias,
        'carrito': carrito_obj,
    }
    return render(request, "product/producto.html", context)

@permission_required('app.view_producto')
def crear_producto(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        form = FormProducto(request.POST, request.FILES, 
            initial={'fecha':timezone.now()}, 
            instance=Producto(imagen=request.FILES['imagen'], 
            admin=user,            
            ))
        if form.is_valid():
            form.save()
            messages.success(request, "Producto Agregado")
            return redirect("productos:home")
    else:
        form = FormProducto(initial={'fecha':timezone.now()})
        categorias = Categoria.objects.all()
        return render(request, "product/producto_nuevo.html", {
            'categorias': categorias,
            "form": form
        })
    
@permission_required('app.view_producto')
def editar_producto(request, producto_id):
    producto_editado = get_object_or_404(Producto, id=producto_id)
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        producto_editado.admin = user
        form = FormProducto(data=request.POST, files=request.FILES, instance=producto_editado)
        if form.is_valid():
            form.save()
            messages.success(request, "Producto Editado")
            return redirect("productos:home")
    else:
        form = FormProducto(instance = producto_editado)
        categorias = Categoria.objects.all()
        context = {
            'categorias': categorias,
            "producto": producto_editado,
            "form": form
        }
        return render(request, 'product/producto_editado.html', context)

@permission_required('app.view_producto')
def producto_borrado(request, producto_id):
    borrado = get_object_or_404(Producto, id=producto_id)
    borrado.delete()
    messages.success(request, "Producto Eliminado")
    return redirect("productos:home")

@permission_required('app.view_producto')
def categorias(request, categoria_id):
    categoria_id = get_object_or_404(Categoria, id=categoria_id)
    categorias = Categoria.objects.all()
    context = {
        'categorias': categorias,
        'id_cat': categoria_id,
    }
    return render(request, "base/navbar.html", context)

class SearchResultsView(ListView):
    model = Producto
    template_name = 'search/resultado.html'
        
    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Producto.objects.filter(
             Q(titulo__icontains=query) | 
             Q(descripcion__icontains=query)
        )
        return object_list 
 
def contacto(request):
    data = {
        'form': ContactoForm()
    }
    
    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Mensaje Enviado")

        else:
            data["form"] = formulario

    return render(request, 'templates/inicio.html', data)

@permission_required('app.view_producto')
def categoria(request):
    data = {
        'form': CategoriaForm()
    }
    
    if request.method == 'POST':
        formulario = CategoriaForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Marca Agregada")
        else:
            data["form"] = formulario

    return render(request, 'templates/categoria.html', data)


@permission_required('app.view_producto')
def listar(request):
    productos = Contacto.objects.all()
    page = request.GET.get('page',1)
    try:
        paginator = Paginator(productos, 3)
        productos = paginator.page(page)
    except:
        raise Http404

    data = { 
        'entity': productos,
        'paginator': paginator
    }

    return render(request, "product/listar.html", data)

templates/product/listar.html
{% extends "base.html" %}
{% block content %}

<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
rel="stylesheet"
/>

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="w3-padding-64 w3-content w3-text-grey" >
<section class="vh-150" >
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <h4 class="text-center my-3 pb-3">Mensajes</h4>
              <table class="table mb-4">
                {% for p in entity %}
                <thead>
                  <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Correo</th>
                    <th scope="col">Mensaje</th>
                    <th scope="col"></th>
                    
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ p.nombre | capfirst }}</td>
                    <td>{{ p.correo  }}</td>
                    <td >{{ p.mensaje  }}</td>
                    <td><button type="submit" class="btn btn-success ms-1">Responder</button></td>     
                      
                  </tr>
                </tbody>
                {% endfor %}
              </table>
              {% include 'product/paginator.html' %}
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% endblock %}

templates/product/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

templates/product/producto.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block content  %}

<!-- About Container -->
<div class="w3-container">   
     <div class="w3-content" style="max-width:700px">                 
       <h5 class="w3-center w3-padding-64"><span class="w3-tag w3-wide">{{ producto.categoria  | capfirst }}</span></h5>
          <p>{{ producto.descripcion  | capfirst }}</p>
          <p><strong>Precio:</strong> ${{ producto.precio | intword| intcomma }}</p>
          <div class="d-flex justify-content-center align-items-center flex-wrap">
               <img src="{{ producto.imagen.url }}" style="width:100%;max-width:500px" class="w3-margin-top">
               <div class="d-flex justify-content-center mt-3">
                   {% if perms.app.view_producto %}
                   <a href="{% url 'productos:editar_producto' producto.id %}" class="btn btn-dark">Editar</a>
                   <a href="{% url 'productos:producto_borrado' producto.id %}" class="btn btn-dark ms-3">Borrar</a>
                   {% endif %}
                   {% if not perms.productos.add_producto %}
                       {% if request.user.is_authenticated %}
                           {% include 'carrito/actualizar_carrito.html' with producto=producto carrito=carrito %}
                       {% else %}
                           <a href="{% url 'login' %}" class="btn btn-success">Agregar al carrito</a>
                       {% endif %}
                   {% endif %}
               </div>
           </div>
           
</div>
{% endblock %}

templates/product/producto_editado.html
{% extends "base.html" %}
{% block content %}

<div class="container pb-5">
    <h3 class="text-center mb-3">Editar Producto</h3>
    <form enctype="multipart/form-data" action="{% url 'productos:editar_producto' producto.id %}" method="post" class="fomulario">
        {% csrf_token %}
        <div class="mb-3 form-floating">
            {{ form.titulo }} {{ form.titulo.errors }}
            <label for="titulo">Título</label>
        </div>
        <div class="mb-3 form-floating">
            {{ form.urlpago }} {{ form.urlpago.errors }}
            <label for="urlpago">Url Flow:</label>
        </div>
        <div class="bloque row pb-5">
            <div class="imagen col">
                <div class="mb-3">
                    <label for="imagen_input"  class="row ms-1 mb-3">IMAGEN</label>
                    <div class="">
                        <img src="{{ producto.imagen.url }}" class="text-center" width="120" height="120" alt="{{ producto.titulo }}"><br> 
                        {{ form.imagen }} {{ form.imagen.errors }}
                    </div>
                </div>
            </div>
            <div class="contenido-form col">
                <div class="mb-3 form-floating">
                    {{ form.categoria }} {{ form.categoria.errors }}
                    <label for="categoria">Categoría</label>
                </div>
                <div class="visually-hidden">
                   {{ form.fecha }} {{ form.fecha.errors }}
                </div>
                <div class="mb-3 form-floating">
                    {{ form.descripcion }} {{ form.descripcion.errors }}
                    <label for="descripcion">Descripción</label>
                </div>
                <div class="row pb-3 fila">
                    <div class="col-auto mb-3 me-5 form-floating fila">
                        {{ form.precio }} {{ form.precio.errors }}
                        <label for="precio" class="ms-2">Precio</label>
                    </div>
                    <div class="col-auto fila">
                        <div class="btn-group col-auto ">
                            <a href="{% url 'productos:producto_borrado' producto.id %}" class="btn btn-dark ms-5 me-3 p-3">BORRAR</a>  
                            <input type="submit" class=" col-auto btn btn-dark ms-4 me-0 p-3" value="EDITAR">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="abajo"></div>

{% endblock %}

templates/product/producto_nuevo.html
{% extends "base.html" %}
{% block content %}


<style>
    * {
        box-sizing: border-box;
    }
    
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 20px;
    }
    
    h2 {
        text-align: center;
    }
    
    .form-group {
        margin-bottom: 20px;
    }
    
    .form-group label {
        display: block;
        font-weight: bold;
        margin-bottom: 5px;
    }
    
    .form-group input,
    .form-group textarea,
    .form-group select {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        resize: vertical;
    }
    
    .form-group select {
        height: 38px;
    }
    
    .form-group input[type="file"] {
        padding: 5px;
    }
    
    .form-group::after {
        content: "";
        display: table;
        clear: both;
    }
    
    @media screen and (min-width: 768px) {
        .form-group {
            display: flex;
            align-items: center;
        }
        
        .form-group label {
            flex-basis: 150px;
            margin-bottom: 0;
        }
        
        .form-group input,
        .form-group textarea,
        .form-group select {
            flex: 1;
        }
        
        .form-group input[type="file"] {
            padding: 0;
        }
    }
</style>

<div class="w3-padding-64 w3-content w3-text-grey" >
<form enctype="multipart/form-data" action="{% url 'productos:producto_nuevo' %}" method="post" class="fomulario">
    {% csrf_token %}

    
    <div class="form-group">
        <label for="titulo">Ubicacion:</label>
        {{ form.titulo }} {{ form.titulo.errors }}   
     </div>

     <div class="form-group">
        <label for="urlpago">Url Flow:</label>
        {{ form.urlpago }} {{ form.urlpago.errors }}   
     </div>

    <div class="form-group">
        <label for="precio">Precio:</label>
        {{ form.precio }} {{ form.precio.errors }}     
     </div>
    
    <div class="visually-hidden" >
        <label for="fecha">Fecha:</label>
        {{ form.fecha }} {{ form.fecha.errors }}     
     </div>
    
    <div class="form-group">
        <label for="descripcion">Descripción:</label>
        {{ form.descripcion }} {{ form.descripcion.errors }}
    </div>
    
    <div class="form-group">
        <label for="categoria">Comuna:</label>
            {{ form.categoria }} {{ form.categoria.errors }}    
     </div>

    <div class="form-group">
        <label for="imagen">Imagen:</label>
        {{ form.imagen }} {{ form.imagen.errors }}    
    </div>
    
    <div class="form-group">
        <input type="submit" value="Enviar"> 
    </div>
</form>
<div style="text-align: center;">
    <a href="https://www.flow.cl/app/web/cobro.php">Generar Pago Flow</a>  
</div>
</div>


{% endblock %}