JKSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("productos.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registro/', include("usuarios.urls")),
    path('carrito/', include("carritos.urls", namespace="carrito")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django import urls
from django.urls import path, re_path
from . import views

from .views import SearchResultsView, categoria, contacto, listar

app_name = "productos"
urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('home/', views.home, name="home"),
    path('acerca/', views.acerca, name="acerca"),
    path('resultado/', SearchResultsView.as_view(), name="resultado"),
    path('producto/<int:producto_id>', views.producto, name="producto"),
    path('producto_nuevo', views.crear_producto, name="producto_nuevo"),
    path('editar_producto/<int:producto_id>', views.editar_producto, name="editar_producto"),
    path('borrar_producto/<int:producto_id>', views.producto_borrado, name="producto_borrado"),
    path('contacto/', contacto, name="contacto"),
    path('categoria/', categoria, name="categoria"),
    path('listar/', listar, name="listar"),



]

templates/acerca.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="card container mt-5">
    <div class="card-header text-center ">
        <h5 class="card-title">Acerca de Music Pro</h5>
    </div>
    <div class="card-body ">    
        <p class="card-text">Music Pro es una tienda de música excepcional que ofrece una amplia variedad de productos para todos los amantes de la música.
             Desde instrumentos musicales de alta calidad hasta equipos de grabación profesionales, esta tienda es el destino perfecto para músicos de todos
              los niveles y géneros. Con un ambiente acogedor y un equipo de expertos apasionados por la música, Music Pro se enorgullece de ofrecer
               una experiencia de compra única y personalizada.</p>

               <p class="card-text"></p>Al ingresar a Music Pro, te encontrarás con una extensa selección de instrumentos musicales de renombre. Desde guitarras eléctricas y acústicas
                hasta teclados, baterías y equipos de viento, esta tienda tiene todo lo que necesitas para expresarte a través de la música. Además, cuentan con
                 una amplia variedad de accesorios, como cuerdas, baquetas, afinadores y estuches protectores, para asegurarte de tener todo lo necesario para 
                 mantener tus instrumentos en perfecto estado.</p>
                 
                 <p class="card-text"></p>Pero Music Pro no se limita solo a instrumentos. También ofrecen una gama completa de equipos de grabación y producción musical. 
                 Desde micrófonos y interfaces de audio hasta software de edición y monitores de estudio, podrás crear tus propias composiciones y grabaciones
                  de alta calidad. El personal de Music Pro está capacitado para asesorarte en la elección de los productos adecuados para tus necesidades y
                   presupuesto, brindándote una atención personalizada y profesional.
            </p>
    </div>
</div>
<div class="abajo2"></div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<html lang="en">
  <head> 
    {% include 'base/head.html' %}
  </head>
  <body>
      {%include 'base/header.html' %} 
      {%include 'base/navbar.html' %}
  
      <div class="container-fluid mb-5">
          {% block content %}{% endblock %}
      </div>
  
      {% include 'base/footer.html' %}
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


      <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

      {% if messages %}
          {% for m in messages %}
          <script>
              Swal.fire({
                  "title":"Cambios Guardados",
                  "text": "{{m}}",
                  "icon":"success"
              })
          </script>
          {% endfor %}
      {% endif %}

      <script>
        // Automatic Slideshow - change image every 4 seconds
        var myIndex = 0;
        carousel();
        
        function carousel() {
          var i;
          var x = document.getElementsByClassName("mySlides");
          for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";  
          }
          myIndex++;
          if (myIndex > x.length) {myIndex = 1}    
          x[myIndex-1].style.display = "block";  
          setTimeout(carousel, 4000);    
        }
        
        // Used to toggle the menu on small screens when clicking on the menu button
        function myFunction() {
          var x = document.getElementById("navDemo");
          if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
          } else { 
            x.className = x.className.replace(" w3-show", "");
          }
        }
        
        // When the user clicks anywhere outside of the modal, close it
        var modal = document.getElementById('ticketModal');
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }
        </script>
  
          {% block js %}
          {% endblock %}
          
  </body>
</html>

templates/categoria.html
{% extends "base.html" %}
{% block content %}


<div class="w3-padding-64 w3-content w3-text-grey" id="contact">
    <h3 class="text-center mb-3">Agregar Comuna</h3>

    <div class="text-center mb-3">

        <form enctype="multipart/form-data" action="{% url 'productos:categoria' %}" method="post" class="formulario">
            {% csrf_token %}
    
            <div class="mb-3 form-floating">
                <label for="descripcion"></label>
                {{ form.descripcion.errors }}
                {{ form.descripcion }}
                <input type="submit" value="Agregar">
    
            </div>        
        </form>
    </div>       
</div>

{% endblock %}

templates/contacto.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- Contact Section -->
<div class="w3-padding-64 w3-content w3-text-grey" id="contact">
    <h2 class="w3-text-light-grey">Contactanos</h2>
    <hr style="width: 200px" class="w3-opacity">

    <div class="w3-section">
        <p><i class="fa fa-map-marker fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Santiago, Chile</p>
        <p><i class="fa fa-phone fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Phone: +569 36703680</p>
        <p><i class="fa fa-envelope fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Email: musicpro@musicpro.com</p>
    </div><br>
    <p> Envianos Tu Mensaje!</p>

    <form enctype="multipart/form-data" action="{% url 'productos:contacto' %}" method="post" class="formulario">
        {% csrf_token %}
        <p><input class="w3-input w3-padding-16" type="text" placeholder="Nombre" required name="nombre"></p>
        <p><input class="w3-input w3-padding-16" type="text" placeholder="Correo" required name="correo"></p>
        <p><input class="w3-input w3-padding-16" type="text" placeholder="Mensaje" required name="mensaje"></p>
        <p>
            <button class="w3-button w3-light-grey w3-padding-large" type="submit">
                <i class="fa fa-paper-plane"></i> Enviar Mensaje
            </button>
        </p>
    </form>
<!-- End Contact Section -->
</div>






{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block content %}


<style>
  .w3-card {
    text-align: center;
  }

  .w3-card img {
    display: block;
    margin: 0 auto;
  }

  
</style>
<style>
  @keyframes pulsate {
    0% {
      transform: scale(1);
      box-shadow: none;
    }
    50% {
      transform: scale(1.1);
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }
    100% {
      transform: scale(1);
      box-shadow: none;
    }
  }
  
  .pulsating-link {
    animation: pulsate 1.5s infinite;
  }
  
  .w3-button.w3-block {
    overflow: hidden;
  }
  </style>
  


<!-- Team Section 1 -->

<div class="w3-container" style="padding:128px 16px" id="team">
  <h3 class="w3-center">ESTACIONAMIENTOSS</h3>
  <p class="w3-center w3-large">Busca tu espacio.</p>


  <div class="w3-row-padding">
    {% for productos in primeros_productos %}
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div style="text-align: center;" class="w3-display-center w3-black w3-padding">{{ productos.categoria | capfirst }}</div>
        
        <div style="height: 100%">
          <img src="{{ productos.imagen.url }}" alt="House" style="width: 100%; height: 100%" class="pulsating-image">
        </div>
      
        <p style="text-align: center; font-weight: bold;">$ {{ productos.precio | intword | intcomma }}</p>
        <p style="text-align: center;"><a onclick="window.location.href = '{{ productos.urlpago }}'" class="w3-buttom w3-button pulsating-link" style="background-color: rgb(14, 13, 13); color: white; border-radius: 10px;"><i></i> Arrendar</a></p>
        <p style="text-align: center;"><a href="{% url 'productos:producto' productos.id %}" class="w3-button w3-button" style="background-color: rgb(14, 13, 13); color: white; border-radius: 10px;"><i></i> Ver</a></p>
      </div>
    </div>
    {% endfor %}
  </div>
  




{% endblock %}

templates/inicio.html
{% load static %}
{% url 'productos:inicio' as inicio %}
{% url 'productos:home' as home %}

<!DOCTYPE html>
<html>
<head>
  <title>Parking Site</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="icon" type="image/x-icon"  href='{% static "css/icono.png" %}' />
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

body, html {
  height: 100%;
  line-height: 1.8;
}

/* Full height image header */
.bgimg-1 {
  background-position: center;
  background-size: cover;
  background-image: url("/w3images/mac.jpg");
  min-height: 100%;
}

.w3-bar .w3-button {
  padding: 16px;
}


.video-container {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
}

.video-container video {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>
</head>
<body>

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-card" id="myNavbar">
    <a href="/" class="w3-bar-item w3-button w3-wide">Parking Site</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      <a href="#team" class="w3-bar-item w3-button"></i> ESTACIONAMIENTOS</a>
      <a href="#contact" class="w3-bar-item w3-button"></i> CONTACTO</a>
      <a href="#about" class="w3-bar-item w3-button">ACERCA</a>

    </div>
    <!-- Hide right-floated links on small screens and replace them with a menu icon -->

    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
</div>

<!-- Sidebar on small screens when clicking the menu icon -->
<nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large" style="display:none" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">SALIR</a>
  <a href="#team" onclick="w3_close()" class="w3-bar-item w3-button">ESTACIONAMIENTOS</a>
  <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button">CONTACTO</a>
  <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">ACERCA</a>

</nav>

<!-- Header with full-height image -->
<header class="bgimg-1 w3-display-container w3-grayscale-min" id="home">
  <div class="video-container">
    <video autoplay loop muted>
      <source src="/media/img/video.mp4" type="video/mp4">
    </video>
  </div>
  <div class="w3-display-middle w3-display-center w3-text-white" style="padding:48px">
    <img src="/media/img/ps.png" alt="Start something that matters" class="w3-jumbo w3-hide-small">
    <img src="/media/img/ps.png" alt="Start something that matters" class="w3-xxlarge w3-hide-large w3-hide-medium">
    <span class="w3-xxlarge w3-hide-large w3-hide-medium"></span><br>
    <div class="w3-display-container w3-center" style="padding-top: 24px;">
      <a  id="miBoton" class="w3-button pulsating-button w3-white w3-padding-large w3-large w3-opacity w3-hover-opacity-off">Ingresar</a>
    </div>
    
  </div> 

  <div class="w3-display-bottomleft w3-text-grey w3-large" style="padding:24px 48px">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
  </div>
</header>

  



<!-- Team Section -->
{% load static %}
{% load humanize %}

{% block content %}

<style>
  @keyframes pulsate {
    0% {
      transform: scale(1);
    }
    50% {
      transform: scale(1.1);
    }
    100% {
      transform: scale(1);
    }
  }
  
  .pulsating-image {
    animation: pulsate 1.5s infinite;
  }
  </style>
<!-- Project Section -->
<div class="w3-container w3-padding-32" id="team">
  <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16"  style="text-align: center;">ESTACIONAMIENTOS RECIENTES</h3>
</div>


<div class="w3-row-padding">
  {% for productos in primeros_productos %}
  <div class="w3-col l3 m6 w3-margin-bottom">
    <div class="w3-display-container">
      <div   style="text-align: center;" class="w3-display-center w3-black w3-padding">{{ productos.categoria | capfirst }}</div>
      


      <div style="height:100%">
        <img src="{{ productos.imagen.url }}" alt="House" style="width:100%; height:100%"  class="pulsating-image">
    </div>
    
    <p style="text-align: center; font-weight: bold;">$ {{ productos.precio | intword | intcomma }}</p>
  </div>
  </div>
  {% endfor %}
</div>


{% endblock %}

















<!-- Modal for full size images on click-->
<div id="modal01" class="w3-modal w3-black" onclick="this.style.display='none'">
  <span class="w3-button w3-xxlarge w3-black w3-padding-large w3-display-topright" title="Close Modal Image">×</span>
  <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
    <img id="img01" class="w3-image">
    <p id="caption" class="w3-opacity w3-large"></p>
  </div>
</div>


<!-- Contact Section -->

<style>
  @keyframes pulsate {
    0% {
      transform: scale(1);
    }
    50% {
      transform: scale(1.1);
    }
    100% {
      transform: scale(1);
    }
  }
  
  .pulsating-button {
    animation: pulsate 1.5s infinite;
  }
  </style>
  
<div class="w3-container" style="padding:128px 16px">
<div class="w3-padding-64 w3-content w3-text-grey" id="contact">
  <h3 class="w3-center">CONTACTO</h3>
  <p class="w3-center w3-large"></p>

  <form enctype="multipart/form-data" action="{% url 'productos:contacto' %}" method="post" class="formulario">
      {% csrf_token %}
      <p><input class="w3-input w3-padding-16" type="text" placeholder="Nombre" required name="nombre"></p>
      <p><input class="w3-input w3-padding-16" type="text" placeholder="Correo" required name="correo"></p>
      <p><input class="w3-input w3-padding-16" type="text" placeholder="Mensaje" required name="mensaje"></p>
      <p style="text-align: center;">
        <button class="w3-button w3-light-grey w3-padding-large pulsating-button" type="submit">
            <i class="fa fa-paper-plane"></i> Enviar Mensaje
        </button>
    </p>
    
  </form>

</div>
</div>

<!-- About Section -->
<div class="w3-container w3-light-grey" style="padding:128px 16px" id="about">
  <h3 class="w3-center">ACERCA DE PARKING SITE</h3>
  
  <div class="w3-row-padding w3-center" style="margin-top:64px">
    <div class="w3-quarter">
      <i class="fa fa-sign-in w3-margin-bottom w3-jumbo"></i>
      <p class="w3-large">Registro</p>
    </div>
    <div class="w3-quarter">
      <i class="fa fa-shopping-cart w3-margin-bottom w3-jumbo"></i>
      <p class="w3-large">Arriendos</p>
    </div>
    <div class="w3-quarter">
      <i class="fa fa-tasks w3-margin-bottom w3-jumbo"></i>
      <p class="w3-large">Calidad</p>
    </div>
    <div class="w3-quarter">
      <i class="fa fa-plane w3-margin-bottom w3-jumbo"></i>
      <p class="w3-large">Accesibilidad</p>
    </div>
  </div>
</div>
  

<!-- Footer -->
<footer class="w3-center w3-black w3-padding-64">
  <a href="#home" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>Subir</a>
  <div class="w3-xlarge w3-section">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
  </div>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-text-green">ParkingSite.com</a></p>
</footer>
 
<script>
// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}


// Toggle between showing and hiding the sidebar when clicking the menu icon
var mySidebar = document.getElementById("mySidebar");

function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
  } else {
    mySidebar.style.display = 'block';
  }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
}
</script>

<script>
  // Obtén el botón por su ID
  var boton = document.getElementById("miBoton");

  // Agrega el evento de clic al botón
  boton.addEventListener("click", function() {
      // Muestra la alerta de Sweet Alert
      Swal.fire({
          title: "Bienvenido a Parking Site",
          text: "{{m}}",
          icon: "success",
          timer: 1000,
      }).then(function() {
          // Redirige a la página deseada
          window.location.href = "/accounts/login/";
      });
  });
</script>
<!-- Incluye Sweet Alert -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


{% if messages %}
    {% for m in messages %}
    <script>
        Swal.fire({
            "title":"Cambios Guardados",
            "text": "{{m}}",
            "icon":"success"
        })
    </script>
    {% endfor %}
{% endif %}


</body>
</html>